theme = "rose_pine"

[editor]
shell = ["fish", "-c"]
rainbow-brackets = true
end-of-line-diagnostics = "hint"
color-modes = true
true-color = true
rulers = [120]
cursorline = true
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]
bufferline = "multiple"
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
# wrap-indicator = "â†ª "

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spacer", "file-name", "file-modification-indicator"]
center = ["version-control"]
right = ["diagnostics", "position", "separator", "total-line-numbers", "spacer", "file-encoding"]

# Shortcurts
# move block up/down
[keys.normal]
A-S-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
A-S-j = [ "extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before" ]

[keys.select]
A-S-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
A-S-j = [ "extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before" ]
