theme = "rose_pine"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
rainbow-brackets = true
end-of-line-diagnostics = "hint"
color-modes = true
true-color = true

[editor.inline-diagnostics]
cursor-line = "warning"


[editor.indent-guides]
render = true
character = "." #"â•Ž"
skip-levels = 0

[keys.normal]
A-S-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
A-S-j = [ "extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before" ]

[keys.select]
A-S-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
A-S-j = [ "extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before" ]
